# Generated by Django 3.2.9 on 2022-03-18 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
    ]
