# Generated by Django 3.2.9 on 2022-03-22 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_carousel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carousel',
            name='text',
        ),
        migrations.AddField(
            model_name='carousel',
            name='sub_title',
            field=models.CharField(default=1, max_length=50),
        ),
        migrations.AddField(
            model_name='carousel',
            name='title',
            field=models.CharField(default=1, max_length=50),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='image',
            field=models.ImageField(upload_to='pics/%y/%m/%id'),
        ),
    ]
