# Generated by Django 3.2.9 on 2022-03-02 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_schooluniform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schooluniform',
            name='description',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
